# Nornir Hosts File 
---
r1: 
  hostname: 10.99.99.10 
  groups: 
    - iosv
  data:
    interfaces: {"lo1": "1.1.1.1", "lo2": "1.1.1.2"}
  connection_options:
    napalm:
      extras:
        optional_args:
          secret: cisco

r2: 
  hostname: 10.99.99.11
  groups: 
    - iosv

r3: 
  hostname: 10.99.99.12
  groups: 
    - iosv

j1:
  hostname: 10.99.99.30
  groups:
    - juniper

devxe1:
  hostname: ios-xe-mgmt.cisco.com
  platform: ios
  port: 8181
  groups:
    - devnet

devxe2:
  hostname: ios-xe-mgmt.latest.cisco.com
  platform: ios
  port: 8181
  groups:
    - devnet